### ISSUE TITLE
clone the repo

### ISSUE THREAD

**Issue by Parisa-Bagherzadeh** [ibrahimgb/robot-navigation-using-deep-reinforcement-learning#2]
i cloned the repo but no folders are downloaded, how to solve this?

warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by brahimgb** [comment]
2 solutions possible: 
fork the project and work from there.
download as a zip and run it on your local machine.
